import { notFound } from "next/navigation";
import { Mail } from "lucide-react";
import { db } from "@/lib/db";
import {
  Badge,
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  EmptyState,
  PageHeader,
} from "@/components/ui";
import { relativeTime } from "@/lib/utils";

export const metadata = { title: "Dev inbox" };
export const dynamic = "force-dynamic";

/**
 * Everything the app would have emailed, when no provider key is configured.
 * This is what makes magic links, invitations, and (from Phase 2) campaigns
 * testable before a sending domain exists.
 */
export default async function DevInboxPage() {
  // Never expose captured mail from a real deployment.
  if (process.env.NODE_ENV === "production") notFound();

  const messages = await db.devInbox.findMany({
    orderBy: { createdAt: "desc" },
    take: 50,
  });

  return (
    <div className="mx-auto max-w-4xl space-y-6 px-4 py-10">
      <PageHeader
        title="Dev inbox"
        description="Outbound mail is captured here because no email provider is configured. Add RESEND_API_KEY to send for real."
      />

      {messages.length === 0 ? (
        <Card>
          <EmptyState
            icon={Mail}
            title="Nothing captured yet"
            description="Request a magic link or invite a teammate and it will show up here."
          />
        </Card>
      ) : (
        <div className="space-y-3">
          {messages.map((message) => (
            <Card key={message.id}>
              <CardHeader>
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <CardTitle className="text-sm">{message.subject}</CardTitle>
                  <div className="flex items-center gap-2">
                    <Badge variant="outline">{message.channel}</Badge>
                    <span className="text-muted-foreground text-xs">
                      {relativeTime(message.createdAt)}
                    </span>
                  </div>
                </div>
                <p className="text-muted-foreground text-xs">
                  To {message.to} · from {message.from}
                </p>
              </CardHeader>
              <CardContent>
                <div
                  className="prose prose-sm dark:prose-invert [&_a]:text-primary max-w-none text-sm [&_a]:underline"
                  // Content is generated by this app's own templates, not user
                  // input, and this page is development-only.
                  dangerouslySetInnerHTML={{ __html: message.body }}
                />
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
